### GET ALL LABORATORIES
GET http://localhost:8000/api/laboratories HTTP/1.1

### GET ALL PHARMACIES BY CITY
GET http://localhost:8000/api/pharmacies?city=London HTTP/1.1

### CREATE AN ORDER
POST http://localhost:8000/api/order HTTP/1.1
Content-Type: application/json

{
  "product": "Smecta",
  "quantity": "7",
  "laboratory": "Servier"
}

### REGISTER
POST http://localhost:8000/api/register HTTP/1.1
Content-Type: application/json

{
  "name": "Servier",
  "email": "servier-lab@gmail.com",
  "password": "azerty",
  "ispharmacy": "false"
}

### AUTHENTIFICATION
POST http://localhost:8000/api/login HTTP/1.1
Content-Type: application/json

{
  "email": "servier-lab@gmail.com",
  "password": "azerty"
}

# {
#   "email": "pharma-odyssee@gmail.com",
#   "password": "azerty"
# }

### CREATE A PHARMACY
POST http://localhost:8000/api/pharmacy/new HTTP/1.1

{
  "email": "Odyssee",
  "password": "Marseille"
}
